# This file was auto-generated by /home/shuyy/nwchem-7.0.0-release/contrib/distro-tools/build_nwchem
export NWCHEM_TOP=/home/shuyy/nwchem-7.0.0-release
export NWCHEM_TARGET=LINUX64
export NWCHEM_MODULES="all"
export NWCHEM_MPIF_WRAP="/usr/local/bin/mpif90"
export NWCHEM_MPIC_WRAP="/usr/local/bin/mpicc"
export NWCHEM_MPICXX_WRAP="/usr/local/bin/mpicxx"
export NWCHEM_LONG_PATHS=Y
export USE_NOFSCHECK=Y
export USE_MPI=y
export USE_MPIF=y
export USE_MPIF4=y
export MPI_INCLUDE="-I/usr/local/include -I/usr/local/lib"
export MPI_LIB="-L/usr/local/lib"
export LIBMPI="-lmpi_usempif08 -lmpi_usempi_ignore_tkr -lmpi_mpifh -lmpi"
export FC=gfortran
export CC=gcc
export CXX=g++
export ARMCI_NETWORK=MPI-MT
export MSG_COMMS=MPI
export PYTHON_EXE=/usr/bin/python
export PYTHONVERSION=2.7
export USE_PYTHON64=yes
export PYTHONPATH=./:/home/shuyy/nwchem-7.0.0-release/contrib/python/
export PYTHONHOME=/usr
export PYTHONLIBTYPE=a
function renwc()
{
   make FC=$FC ; pushd $NWCHEM_TOP/src ; make FC=$FC link ; popd
}
